### ISSUE TITLE
Add token key but still got error: User not authorized

### ISSUE THREAD

**Issue by lebaphi** [RadiusNetworks/flybuy-android-example#4]
Hi, 
I created an API key from my account: https://account.radiusnetworks.com/personal_tokens.
Then I download the sample project, put my API token in line 17 in ExampleApplication.kt as the document said
```
override fun onCreate() {
        super.onCreate()
        FlyBuyCore.configure(this, "my_api_token")
        PickupManager.getInstance().configure(this)
    }
```
When I launch the app on the Android emulator, click on the button `Redeem Order` 
![image](https://user-images.githubusercontent.com/26705621/119941903-62a98b00-bfbb-11eb-9609-04985a20c659.png)

Then I see this error:
![image](https://user-images.githubusercontent.com/26705621/119941515-e616ac80-bfba-11eb-86d4-6b3d2f2738c4.png)

I'm not sure why? Could you please have a look at this?

Thanks,
Phile

**Comment by keithyoder** [comment]
The SDK token is not the same thing as the API token.  Radius Networks needs to supply you with an SDK token.  Please request the token via your account manager at Radius.

**Comment by lebaphi** [comment]
I got the token but it still the same result. Maybe this token doesn't work with the sample project? Do you have a sample project written in Java?

**Comment by mohanenm** [comment]
resolved via email
